@startuml
Class Bala{

}
Class Invader{
    +Disparar()
    +Mover
}
Class Nave{
    +Disparar()
}
Class Jugador{
    +MoverDerecha()
    +MoverIzquierda()
}
Class Ventana{

}

Jugador o-- Nave
Invader --|> Nave
Nave o-- Bala

@enduml