@startuml
Class Bala{

}
Class Invader{
    +Pilotar()
}
Class Nave{

}
Class Jugador{
    +Pilotar()
}
Class Ventana{

}
Class Juego{
}

Juego *-- Ventana
Juego *-- Jugador
Juego *-- Invader
Jugador o-- Nave
Invader --|> Nave
Nave o-- Bala

@enduml